meta_product_name: "Get to the fest"
meta_title: "Get To The Fest - A simple tool to find festivals"
meta_description: "Discover festivals you could like by matching artists you follow on Spotify - It's really simple, all you have to do is to click below"
meta_image: "cover.jpg"
twitter_account: "@product_twitter_account"
